[package]
name = "pns-ddns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-api.workspace = true
sp-blockchain.workspace = true
sp-block-builder.workspace = true

axum.workspace = true
tracing.workspace = true

pns-types = { path = "../pns-types" }
pns-runtime-api = { path = "../pns-runtime-api" }
pns-registrar = { path = "../pns-registrar" }
